spring.application.name=interaction-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/interactiondb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/