server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/api/pets/**
        - id: auth-service
          uri: lb://authservice
          predicates:
            - Path=/api/auth/**
        - id: adoption-service
          uri: lb://adoption-service
          predicates:
            - Path=/api/adoption-requests/**
        - id: interaction-service
          uri: lb://interaction-service
          predicates:
            - Path=/api/favorites/**, /api/reviews/**, /api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true