server:
  port: 8083

spring:
  application:
    name: adoption-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petdb}
    username: ${SPRING_DATASOURCE_USERNAME:odoo}
    password: ${SPRING_DATASOURCE_PASSWORD:odoo}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
